server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active:
    - dev
    
datasource:
  contactdirectory:
    url: jdbc:h2:contact
    username: hemanthjamili
    password: password
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      